### ISSUE TITLE
10 grammatica vragen per toets

### ISSUE THREAD

**Issue by vangeest** [vangeest/woots#2]
Het zijn er nu 5, min of meer in verhouding met het aantal opgaven dat we heben. De sectie Frans geeft voorkeur aan een gelijke verdeling van de 3 onderdelen: woordjes FA-NL, woordjes NL-FA, Grammatica

**Comment by stemvork** [comment]
Commit 651b0454 heeft dit aangepast. Wat is de consequentie van deze verandering?
