### ISSUE TITLE
Verbeter layout Fill vraag

### ISSUE THREAD

**Issue by vangeest** [vangeest/woots#6]
Kijk wat mogelijk is om de layout te verbeteren.
Bijvoorbeeld:
- invulveld op de puntjes in de zin
- suggestie tussen () achter invulveld plaatsen
- de vraag (achter het nummer) is nu leeg, alles staat in het antwoord veld eronder. een chiquere oplossing zou mooi zijn.

**Comment by stemvork** [comment]
Lijkt simpel genoeg, maar correctheid van het algoritme is hier wel een dingetje, hangt sterk af van input.

Dataset doorgespit, enkele cases uitgezocht om over na te denken:
- Soms wel puntjes, maar de hele zin als antwoord:`Il ... a ... soif.` met antwoord `Il n'a pas soif.`
- Soms wel puntjes, maar afmaken (of hele woord): `Tu regard... où?` met antwoord `es` of `regardes`
- Soms geen puntjes, negatieve versie maken: `On cherche un bon restaurant.` met antwoord `On ne cherche pas un bon restaurant.`

Gestopt met spitten en denken, Excel bestand toegestuurd met een gefilterde dataset: alle speciale fill vragen.

**Comment by vangeest** [comment]
Mijn voorstel is om vooralsnog af te zien van implementatie van dit issue.
Argument: Er blijkt geen eenvoudige manier te zijn om te bepalen waar het invulveld moet (... werkt niet, er zijn vragen met meerdere puntjes). 
Daarbij in gedachte nemende: Het gaat enkel om schoonheid, niet om functionaliteit.
